// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetGuardian.Infrastructure.Persistence;

#nullable disable

namespace PetGuardian.Infrastructure.Migrations
{
    [DbContext(typeof(PetGuardianContext))]
    partial class PetGuardianContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetGuardian.Domain.Entities.Atendimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ATENDIMENTO");

                    b.Property<string>("Anotacoes")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("ANOTACOES");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TipoAtendimento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TIPO_ATENDIMENTO");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("VALOR");

                    b.Property<Guid>("VeterinariaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_VETERINARIA");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinariaId");

                    b.ToTable("PG_ATENDIMENTOS", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("RUA");

                    b.HasKey("Id");

                    b.ToTable("PG_ENDERECOS", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Familia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_FAMILIA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("PG_FAMILIAS", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<bool>("Castrado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CASTRADO");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_FAMILIA");

                    b.Property<byte>("Idade")
                        .HasColumnType("NUMBER(2)")
                        .HasColumnName("IDADE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PORTE");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("RACA");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("SEXO");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId");

                    b.ToTable("PG_PETS", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_TAREFA");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_FAMILIA");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_PET");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PRAZO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TITULO");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("FamiliaId")
                        .IsUnique();

                    b.HasIndex("PetId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PG_TAREFAS", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("EMAIL");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_FAMILIA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SENHA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.HasIndex("FamiliaId");

                    b.ToTable("PG_USUARIOS", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Veterinaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_VETERINARIA");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.ToTable("PG_VETERINARIAS", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Atendimento", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Atendimentos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Veterinaria", "Veterinaria")
                        .WithMany("Atendimentos")
                        .HasForeignKey("VeterinariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Veterinaria");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Familia", "Familia")
                        .WithMany("Pets")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Familia", "Familia")
                        .WithOne()
                        .HasForeignKey("PetGuardian.Domain.Entities.Tarefa", "FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Tarefas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Pet");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("PetGuardian.Domain.Entities.Usuario", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Familia", "Familia")
                        .WithMany("Usuarios")
                        .HasForeignKey("FamiliaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Familia");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Veterinaria", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Endereco", "Endereco")
                        .WithOne()
                        .HasForeignKey("PetGuardian.Domain.Entities.Veterinaria", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Familia", b =>
                {
                    b.Navigation("Pets");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Atendimentos");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Veterinaria", b =>
                {
                    b.Navigation("Atendimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
